services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" 
    volumes:
      - ./frontend:/app 
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000" 
    volumes:
      - ./backend:/app  
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
